before_install:
  - gem update --system 2.1.11
  - gem --version
language: ruby
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.0
