name: CI
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0]
        include:
          - ruby: '2.3'
            bundler: '1'
          - ruby: '2.4'
            bundler: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: Test with Rake
        run: bundle exec rake
