name: CI
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 3.0.0, 2.6 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and test with Rake
        run: |
          gem install bundler -v 2.4.1
          bundle install --jobs 4 --retry 3
          bundle exec rake
